version: '3'
services:
  percona:
    image: percona:5.7
    container_name: percona
    restart: always
    ports:
        - 3316:3306
    environment:
      - MYSQL_DATABASE=skoove
      - MYSQL_USER=skoove
      - MYSQL_PASSWORD=AV1h022m31TPe8H
      - MYSQL_ROOT_PASSWORD=kP1MwuSFR22LcVZ

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    container_name: backend
    restart: always
    volumes:
        - "./backend/:/app"
    depends_on:
      - percona

  nginx:
    image: nginx:1.15.6-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - "./backend/:/app"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - backend
