#!/bin/sh
set -e

cd /app
file="create.lock"
if [ ! -f "$file" ]
then
    echo "1" > create.lock
    cp .env.local .env
    echo "Waiting percona start"
    sleep 60
    echo "Running the migrations"
    php artisan migrate

fi
echo "Starting php-fpm"
exec "$@"
